### ISSUE TITLE
Runnable Docker image

### ISSUE THREAD

**Issue by hwellmann** [glondu/belenios#27]
A self-contained Docker image or a Docker compose file for running the Belenios web server would be much appreciated.

Building an image from sources using completely unknown technologies is too much of an effort for running an evaluation of a software system.

Could it be as simple as adding a missing entrypoint to the `glondu/beleniosbase` image?

**Comment by albanbruder** [comment]
Sadly that is not that easy. The [base image](https://gitlab.inria.fr/belenios/belenios/-/blob/master/Dockerfile_base_environment) does not contain a build of the belenios-server (only the basic opam bootstrap stuff). For the student council elections at our university we created a [basic docker setup](https://gitlab.com/bauhaus/belenios) which could serve as an inspiration how one could setup a docker build cycle (just ignore the customizations for now).

You can try it our with the following `docker-compose.yml`:

```yml
version: "3"

services:
  belenios:
    image: registry.gitlab.com/bauhaus/belenios:1.15
    environment:
      - DOMAIN=localhost
      - MAIL_FROM=admin@example.org
      - MAIL_RETURN_PATH=admin@example.org
      - MAIL_HOST=smtp.example.org
      - MAIL_USER=admin
      - MAIL_PASSWORD=password
      - MAIL_STARTTLS=yes
      - CONTACT=admin@example.org
      - GDPR_POLICY=https://www.belenios.org/gdpr.html
      - AUTH_DEMO_NAME=dummy
      - AUTH_DEMO_PROTO=dummy
      - AUTH_DEMO2_NAME=dummy
      - AUTH_DEMO2_PROTO=dummy
      - AUTH_DEMO2_EXPORT=1
    volumes:
      - belenios:/var/belenios
    ports:
      - 8001:8001

volumes:
  belenios:
```

See the [README](https://gitlab.com/bauhaus/belenios/-/tree/master#configuration) for an explanation of the environment variables. 

Please note that as our election is over this will probably not be maintained and I do no  recommend to use it in production. But I would be happy to help integrating a similar setup into Belenios.
